### ISSUE TITLE
Farbwerte bei Gauge / Plate führen zu Fehlern

### ISSUE THREAD

**Issue by Burki24** [Acer90/SymconModule#33]
Ich erhalte folgenden Fehler:
![image](https://user-images.githubusercontent.com/20765982/120213749-e1a8f880-c233-11eb-82a3-ef4001bde1e4.png)

Bei den Farben war folgendes Eingestellt:

![image](https://user-images.githubusercontent.com/20765982/120213833-fab1a980-c233-11eb-8ecf-a4a2aec1d914.png)

Anbei der Export:

`{
    "ModulID": "{71B93700-9659-97C6-AD83-984C2B44139F}",
    "ModuleName": "SymconJSLiveGauge",
    "Config": {
        "Variable": 25121,
        "min": 0,
        "max": 250,
        "template": "CanvasGauges-Radial",
        "Debug": false,
        "EnableCache": true,
        "CreateOutput": true,
        "TemplateScriptID": 0,
        "EnableViewport": true,
        "IFrameHeight": 0,
        "title_text": "",
        "title_display": false,
        "title_fontSize": 20,
        "title_fontColor": 0,
        "title_fontFamily": "",
        "plate_display": true,
        "plate_unit": "Watt",
        "plate_colorPlate": 65331,
        "plate_colorPlate_Alpha": 0.7,
        "plate_colorPlateEnd": 16711680,
        "plate_colorPlateEnd_Alpha": 0,
        "needle_display": true,
        "needle_Type": "line",
        "needle_start": 50,
        "needle_end": 80,
        "needle_width": 2,
        "needle_colorNeedle": 0,
        "needle_colorNeedle_Alpha": 1,
        "needle_colorNeedleEnd": 0,
        "needle_colorNeedleEnd_Alpha": 1,
        "valuebox_display": false,
        "valuebox_fontSize": 14,
        "valuebox_colorValueBoxBackground": 0,
        "valuebox_colorValueBoxBackground_Alpha": 0,
        "valuebox_fontFamily": "Roboto",
        "progressbar_display": true,
        "progressbar_barWidth": 5,
        "progressbar_barShadow": 19,
        "progressbar_colorBar": 0,
        "progressbar_colorBar_Alpha": 1,
        "progressbar_colorBarProgress": 16384000,
        "progressbar_colorBarProgress_Alpha": 1,
        "ticks_fontFamily": "Roboto",
        "ticks_fontSize": 12,
        "ticks_strokeTicks": true,
        "ticks_highlightsWidth": 5,
        "ticks_minorTicks": 5,
        "ticks_colorMajorTick": 16711680,
        "ticks_colorMinorTicks": 9961729,
        "ticks_colorUnits": 16711680,
        "ticks_colorNumbers": 16711680,
        "animation_rule": "bounce",
        "animation_duration": 5000,
        "Ticks": "[]",
        "Highlights": "[]",
        "radial_startAngle": 90,
        "radial_ticksAngle": 180,
        "linear_tickSide": "both",
        "linear_numberSide": "both",
        "linear_needleSide": "both"
    }
}`

**Comment by Acer90** [comment]
Fixed
