### ISSUE TITLE
Min/Max-Werte in Gauge akzeptieren nur ganze Zahlen

### ISSUE THREAD

**Issue by Burki24** [Acer90/SymconModule#36]
Wenn eine Gauge angelegt werden soll, wo die Skala z.B. von 6,5 bis 8,5 gehen soll, werden die Werte leider gerundet.
Aus:
![image](https://user-images.githubusercontent.com/20765982/121354309-0cc7d200-c92f-11eb-91c0-5bca7bb50f2a.png)

Wird:
![image](https://user-images.githubusercontent.com/20765982/121354393-21a46580-c92f-11eb-997c-2df40e798433.png)

Das kann, wenn die Werte sich im 0,xx Bereich bewegen eher stören als helfen. Geht das abzustellen?

**Comment by Acer90** [comment]
![image](https://user-images.githubusercontent.com/16419981/121704815-6289af00-cad4-11eb-92da-df740ccd2a54.png)
Fix mit nächsten patch
