### ISSUE TITLE
Highlights korrelieren nicht mit den Ticks

### ISSUE THREAD

**Issue by Burki24** [Acer90/SymconModule#37]
Wenn man eine Range bei der Variablen von 6-8 angibt und passend dazu Ticks (alle 0,2) und dann noch alle 0,2 einen Zwischenschritt, werden die Highlights nicht mehr passend dargestellt.

Beispiel:
![image](https://user-images.githubusercontent.com/20765982/121355036-c4f57a80-c92f-11eb-9d80-e4de5cbd634a.png)

Ergibt:

![image](https://user-images.githubusercontent.com/20765982/121355185-e9e9ed80-c92f-11eb-8712-3f515c6a53a0.png)

**Comment by Acer90** [comment]
Bitte configuration file hier noch hochland (drag and drop)

**Comment by Burki24** [comment]
`{
    "ModulID": "{71B93700-9659-97C6-AD83-984C2B44139F}",
    "ModuleName": "SymconJSLiveGauge",
    "Config": {
        "Variable": 0,
        "min": 6,
        "max": 8,
        "template": "CanvasGauges-Radial",
        "Debug": false,
        "EnableCache": true,
        "CreateOutput": true,
        "TemplateScriptID": 0,
        "EnableViewport": true,
        "IFrameHeight": 0,
        "title_text": "Wattverbrauch",
        "title_display": false,
        "title_fontSize": 20,
        "title_fontColor": 0,
        "title_fontFamily": "",
        "plate_display": true,
        "plate_unit": "",
        "plate_colorPlate": 16777215,
        "plate_colorPlate_Alpha": 1,
        "plate_colorPlateEnd": 16777215,
        "plate_colorPlateEnd_Alpha": 1,
        "needle_display": true,
        "needle_Type": "line",
        "needle_start": 0,
        "needle_end": 60,
        "needle_width": 4,
        "needle_colorNeedle": 9737364,
        "needle_colorNeedle_Alpha": 1,
        "needle_colorNeedleEnd": 16711680,
        "needle_colorNeedleEnd_Alpha": 1,
        "valuebox_display": false,
        "valuebox_fontSize": 14,
        "valuebox_colorValueBoxBackground": 0,
        "valuebox_colorValueBoxBackground_Alpha": 0,
        "valuebox_fontFamily": "Roboto",
        "progressbar_display": false,
        "progressbar_barWidth": 28,
        "progressbar_barShadow": 19,
        "progressbar_colorBar": 0,
        "progressbar_colorBar_Alpha": 1,
        "progressbar_colorBarProgress": 16384000,
        "progressbar_colorBarProgress_Alpha": 1,
        "ticks_fontFamily": "Roboto",
        "ticks_fontSize": 12,
        "ticks_strokeTicks": true,
        "ticks_highlightsWidth": 5,
        "ticks_minorTicks": 2,
        "ticks_colorMajorTick": 0,
        "ticks_colorMinorTicks": 16711680,
        "ticks_colorUnits": 65331,
        "ticks_colorNumbers": 0,
        "animation_rule": "bounce",
        "animation_duration": 5000,
        "Ticks": "[{\"Value\":6.8},{\"Value\":7},{\"Value\":7.2},{\"Value\":6.6000000000000005},{\"Value\":6.4},{\"Value\":6.2}]",
        "Highlights": "[{\"From\":7.2,\"To\":7.6000000000000005,\"HighlightColor\":65412,\"HighlightColor_Alpha\":1},{\"From\":7,\"To\":7.2,\"HighlightColor\":16514816,\"HighlightColor_Alpha\":1},{\"From\":7.6000000000000005,\"To\":7.8,\"HighlightColor\":16514816,\"HighlightColor_Alpha\":1},{\"From\":7.8,\"To\":8,\"HighlightColor\":16711680,\"HighlightColor_Alpha\":1},{\"From\":6.8,\"To\":7,\"HighlightColor\":16711680,\"HighlightColor_Alpha\":1}]",
        "radial_startAngle": 45,
        "radial_ticksAngle": 270,
        "linear_tickSide": "right",
        "linear_numberSide": "left",
        "linear_needleSide": "both"
    }
}`

[30241-SymconJSLiveGauge (2).zip](https://github.com/Acer90/SymconModule/files/6628537/30241-SymconJSLiveGauge.2.zip)

**Comment by Acer90** [comment]
Bug entsteht wenn Ticks mit ungleichen abstand definiert werden, der fehler ist in der lib canvasgauges und kann nicht in JSLive behoben werden.
