### ISSUE TITLE
[JSLiveChart][JSLiveRadarChart]Punkte-Einstellungen pro Dataset

### ISSUE THREAD

**Issue by Burki24** [Acer90/SymconModule#41]
Wenn man ein Chart mit mehreren Data-Sets erstellt, können keine unterschiedlichen Punkte (Punkt, Dreieck, Quader,etc.) vergeben werden. Es kriegen alle die gleiche Punktform. Schöner wäre es, wenn man die Punktform pro Dataset vergeben könnte.

**Comment by Acer90** [comment]
Wir so umgesetzt.

Als Override funktion, das man sie oben global definieren kann und im datensatz überschreibt man diesen wert.
