### ISSUE TITLE
[JSLiveGauge]ändert Farbverhältnisse bei Änderung der Präzision

### ISSUE THREAD

**Issue by Burki24** [Acer90/SymconModule#43]
Wenn man bei Präzision die Nachkommastellen einstellt verändert sich auch die Farbgebung der Platte

Nachkommastellen: Keine
![image](https://user-images.githubusercontent.com/20765982/123516422-50933900-d69c-11eb-8cec-eb9c744e3cdf.png)

Nachkomma: Eine
![image](https://user-images.githubusercontent.com/20765982/123516444-60ab1880-d69c-11eb-85dc-502623ac408a.png)

Nachkomma: zwei
![image](https://user-images.githubusercontent.com/20765982/123516460-71f42500-d69c-11eb-8193-bf7be4d17c50.png)

Nachkomma: drei
Keine Änderung der Farben feststellbar

Konnte noch nicht ergründen, wie das womit zusammenhängt.

**Comment by Acer90** [comment]
Ist gefixt
