### ISSUE TITLE
[JSLiveGauge]Schriftgröße in Wert und Einheit passt sich trotz Änderung nicht an

### ISSUE THREAD

**Issue by Burki24** [Acer90/SymconModule#44]
![image](https://user-images.githubusercontent.com/20765982/123548438-180b6200-d765-11eb-8d3c-af09d07d4241.png)
Schriftgröße 10 bei Wert eingetragen

![image](https://user-images.githubusercontent.com/20765982/123548471-2e192280-d765-11eb-8ea4-e209e08a3967.png)
Schriftgröße 20 eingetragen.

Könnte mit der Autoskalierung zusammen hängen.

**Comment by Acer90** [comment]
Schrift kann jetzt unter Plate/Platte geändert werden.
Der Rest wurde bereits in einen neueren Fix geändert.
