### ISSUE TITLE
[JSLiveGauge]Tausenderpunkte beim Wert wären toll

### ISSUE THREAD

**Issue by slausch** [Acer90/SymconModule#45]
Eigentlich alles gesagt. Keine hohe Prio denke ich, aber halt bissl Icing :-)
Danke und Gruss Seppm

**Comment by Acer90** [comment]
Sollte eigentlich schon integriert sein, schau dir mal oben die einstellung **Präzision**

**Comment by slausch** [comment]
![Bildschirmfoto 2021-06-28 um 08 35 59](https://user-images.githubusercontent.com/32709787/123591164-ebe6f400-d7eb-11eb-992a-6fc7839dc0c9.jpg)
Hi,
ich glaub das ist ein Missverständnis. Präzision ist nun super mit den Dezimalstellen rechts vom Komma.
Was ich meinte ist der Tausenderpunkt, also anstatt 1000 dann 1.000
Das finde ich in der aktuellen Version noch nicht.
Wobei ich das vorrangig für den Wert unten meine. Ob ich das bei den Werten im Gauge schön finden würde, bin ich nicht sicher, da wirkt es mit 1000 eigentlich ganz hübsch. Unübersichtlich wird es wohl wenn es 4,5 oder 6-stellig wird.
Schöne Grüße Seppm

**Comment by Acer90** [comment]
Ok, du willst das da 1.000 steht statt 1000
Ich Prüf das mal, aktuell arbeite ich noch an der Nativen Integration in IPSView

**Comment by Acer90** [comment]
erledigt
