### ISSUE TITLE
[JSLiveGauge] Bei Werten unter 100 werden beim Wert führende Nullen ausgegeben

### ISSUE THREAD

**Issue by slausch** [Acer90/SymconModule#46]
7,2 ergibt dann in der Anzeige zB 007,2
Wäre toll wenn die führenden Nullen entfallen könnten.
Schöne Grüße
Seppm

**Comment by Acer90** [comment]
Wie im Forum beschrieben:
https://community.symcon.de/t/modul-beta-jslive/125118/198?u=acer90

Behebung ist ganz oben auf meine Prio und kommt mit nächsten update.

Swen

**Comment by Acer90** [comment]
behoben
