### ISSUE TITLE
[JSLiveDonut] Werte bei zB 2 Datasets nehmen immer zB W ein obwohl zB % bei einem Dataset als Profil angegeben ist

### ISSUE THREAD

**Issue by slausch** [Acer90/SymconModule#49]
Problem: Werte bei zB 2 Datasets nehmen immer zB W ein (beim ersten Dataset so eingestellt) obwohl zB % beim zweiten Dataset als Profil angegeben ist.
![Bildschirmfoto 2021-08-09 um 11 13 07](https://user-images.githubusercontent.com/32709787/128683950-47e67e9b-6b77-4544-ade0-5aa7379e18b1.jpg)
![Bildschirmfoto 2021-08-09 um 11 13 55](https://user-images.githubusercontent.com/32709787/128684052-67518d48-334c-41d7-8700-b43e8aff1820.jpg)
![Bildschirmfoto 2021-08-09 um 11 14 25](https://user-images.githubusercontent.com/32709787/128684122-fb888e0b-c666-483a-b99a-066c193c9a86.jpg)
![Bildschirmfoto 2021-08-09 um 11 15 15](https://user-images.githubusercontent.com/32709787/128684238-20613538-10ef-43aa-bb97-c9ac86caa8a0.jpg)
![Bildschirmfoto 2021-08-09 um 11 15 56](https://user-images.githubusercontent.com/32709787/128684602-99649500-a695-4827-bdc6-c65d7f9464a4.jpg)

Und das kommt dann raus, es ist jeweils "Datalabels show suffix" eingestellt.
![Bildschirmfoto 2021-08-09 um 11 18 26](https://user-images.githubusercontent.com/32709787/128684695-94bb6490-3755-43ef-9a04-a5ef3fa90d0b.jpg)

Wenn ich beim 2.ten Dataset "Datalabels show suffix" ausschalte kommt wie gewünscht gar kein Wert, das ist derzeit mein Workaround.

Was in dem Zusammenhang auch auffiel, es ist nicht so praktisch wenn man bei "Daten" nur für alles die 1 oder 0.1 oder 0.01 einstellen kann. Denn für mein Beispiel hätte ich das zwar gerne mit 1 Stelle bei den Prozentwerten (damit das etwa 100 ergibt) aber bei den grossen Werten der Watt hätte ich es gerne zwecks Lesbarkeit ohne Dezimalstellen. 
Könnte man die Dezimalstellen anstatt Global ggf. je Dataset einstellbar machen?

Vllt noch was der geteilte Donut soll, finde es halt praktisch wenn man nicht nur Watt-Angaben hat sondern auch gleich die Prozentuale Verteilung der Werte. Muss ich allerdings rel. mühsam mit einem Skript bei jeder Änderung eines der 3 Werte neu ausrechnen. Geht aber ganz gut. 

Was mir dann noch "fehlt" ist die Gesamt-Last die sich aus den (hier) drei Werten ergibt. Die muss ich eh ausrechnen. Wenn das allerdings gleich aus dem Modul fallen könnte und zB in der Mitte einstellbar, wäre auch nicht schlecht, das ist aber nice to have weil leicht selbst lösbar.

Generell ist der Donut SUPER!

Schöne Grüße
Seppm

**Comment by Acer90** [comment]
Geplant ist hier das Profil auf den Datensatz umzubauen. Da bei einen Dougnut/Pie ja in einen Datensatz(ein ganzer Ring) immer gleiche werte miteinander verglichen werden.

> Was mir dann noch "fehlt" ist die Gesamt-Last die sich aus den (hier) drei Werten ergibt. Die muss ich eh ausrechnen. Wenn das allerdings gleich aus dem Modul fallen könnte und zB in der Mitte einstellbar, wäre auch nicht schlecht, das ist aber nice to have weil leicht selbst lösbar.

Das sollte am besetn außerhalb des Moduls erledigt werden, grade wenn du mehrere datenstätze verwendest wirkt dieses unübersichtlich.

**Comment by Acer90** [comment]
erledigt
