### ISSUE TITLE
[JSLiveChart] Stacking der Werte geht sporadisch nicht

### ISSUE THREAD

**Issue by slausch** [Acer90/SymconModule#51]
Das Stacking der Variablen geht sporadisch nicht mehr.
Fiel auf bei der Nutzung in einem IPS studio Pro Popup am iPad. Beim IPSViewClient unter Windows passiert es auch. Dauerte aber bis zu 5 x das Popup aufrufen bis richtig dargestellt wurde.
Beim iPad geht es meist beim 2./3.ten Mal.
Falsch sieht es so aus:
![IMG_0633](https://user-images.githubusercontent.com/32709787/129455327-85835408-8962-45b9-9c63-3d8aaf70c78b.PNG)
Man sieht gut dass dunkelgrüne beginnt an der Nullline.

Das Stacking vergisst er nur beim Linken Chart, beim rechten ist das noch nie passiert obwohl es bis auf die Werte recht ähnlich ist. Korrekt sieht es dann so aus:
![IMG_0634](https://user-images.githubusercontent.com/32709787/129455267-20a72597-cb96-4df9-8a35-94c9d1f6458e.PNG)

Könnte sein dass das Problem begann nachdem ich die weisse Linie eingebaut hab. Die hat eine andere Stacking Gruppe da die nicht aufaddiert werden soll. Die ist halt die Summer der anderen 3 Werte und soll in weiss quasi klarer machen dass dies die Summe ist. Hab ich aber erst kürzlich das Archiv aktiviert.

Hier die Konfig.
[44806-SymconJSLiveChart-2.json.zip](https://github.com/Acer90/SymconModule/files/6986928/44806-SymconJSLiveChart-2.json.zip)

Hier die Konfig des rechten Charts das immer stimmte bisher. Hat aber auch die weisse Linie nicht drin.
[25578-SymconJSLiveChart-2.json.zip](https://github.com/Acer90/SymconModule/files/6986929/25578-SymconJSLiveChart-2.json.zip)

Evtl. hab ich den Grund gefunden. Die Stacking Gruppe der weissen Linie war 0. Das geht schon, aber scheinbar vergisst er dann manchmal das Stacking.  Ich beobachte mal ob es nochmal auftritt. Kann es derzeit nicht mehr provozieren.

Und noch ein Effekt beim gleichen Chart. Würde den Tag eigentlich gern mit hoher Dichte haben. Wenn ich das bei den drei Werten (ausser der weissen Linie) umstelle, dann stacked er zum einen nicht und der dunkelgrüne Wert sieht super komisch aus. Zu Anfang noch hohe Dichte dann gerade Linien ? Ggf. hängen die Dinge zusammen? Sonst trenne ich es auch gern.
![IMG_CC0FF8ECA404-1](https://user-images.githubusercontent.com/32709787/129456052-9226c193-e6b4-49bb-b75b-b283ffe6ad06.jpeg)

Danke und Gruss
Seppm

**Comment by Acer90** [comment]
fehler gefunden und behoben fix kommt mit nächsten update.
