### ISSUE TITLE
Samsung Tizen anlegen von Links, Rechts, Oben, Unten und Enter Taste

### ISSUE THREAD

**Issue by Lexren2** [Acer90/SymconModule#52]
Hallo,

als erstes vielen Dank für deine Arbeit, bei mir funktionieren deine Module gut. Hast Du Patron um dich zu unterstützen?

Ich würde gerne Die Fünf Tasten in der Visu anlegendem nicht nur die App zu starten (zB Netflix) sondern eben auch zu bedienen. Ist dies möglich? Leider komme ich nicht weiter...

**Comment by Acer90** [comment]
Erst entschuldige warum es so lange gedauert hat.
Ich will und darf hier kein geld verlangen, ich werden schon durch JetBrains mit einer Lizenz für dieses Projekt unterstützt.

Zu deiner Frage.
Ja das geht, aber wenn du eine App Startest musst kurz warten, da der Fernseher sonst die tasten verschluckt.
Hier mal ein Beispiel code

`
//app starten
SamsungTizen_StartApp($Instance_ID, $appName);

sleep(5); //5 sekunden warten

$keys = "KEY_1;KEY_2;KEY_3;KEY_4"; //Keys mit einen Semikolon trennen
SamsungTizen_SendKeys($Instance_ID, $keys);
`

Acer90
